services:
  postgres:
    image: postgres:17
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq_broker
    restart: always
    ports:
      - "5672:5672"     # AMQP messaging port
      - "15672:15672"   # Management Web UI port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  pgdata:
  rabbitmq_data:
